/**
 * First-party package seeds (Phase 22 / DP6 · Phase 23 / DQ6).
 * package_id is stable and immutable; versions are published immutably.
 */
import type { FirstPartyPackageSeed } from "./package-registry.js";
import type { PackageManifest } from "./package-manifest.js";

const CONTRACTS = { min_core: "0.0.0", min_kernel: "0.0.0" } as const;

function agentManifest(
  packageId: string,
  capabilityId: string,
  displayName: string,
  description: string,
  version: string,
  entrypoint: string,
  permissions: string[],
): PackageManifest {
  return {
    id: packageId,
    kind: "agent",
    version,
    publisher: "at72",
    display_name: displayName,
    description,
    icons: [],
    contracts: { ...CONTRACTS },
    permissions_requested: permissions,
    resources: {
      entrypoint,
      manifests: [`${entrypoint}/agent.manifest.json`],
    },
    pricing: { model: "free" },
    categories: ["first-party"],
    tags: ["first-party", capabilityId],
  };
}

function skillManifest(
  packageId: string,
  capabilityId: string,
  displayName: string,
  description: string,
  version: string,
  entrypoint: string,
): PackageManifest {
  return {
    id: packageId,
    kind: "skill",
    version,
    publisher: "at72",
    display_name: displayName,
    description,
    icons: [],
    contracts: { ...CONTRACTS },
    permissions_requested: [`skill.invoke:${capabilityId}`],
    resources: {
      entrypoint,
      manifests: [`${entrypoint}/skill.manifest.json`],
    },
    pricing: { model: "free" },
    categories: ["first-party"],
    tags: ["first-party", capabilityId],
  };
}

function toolManifest(
  packageId: string,
  capabilityId: string,
  displayName: string,
  description: string,
  version: string,
  entrypoint: string,
): PackageManifest {
  return {
    id: packageId,
    kind: "tool",
    version,
    publisher: "at72",
    display_name: displayName,
    description,
    icons: [],
    contracts: { ...CONTRACTS },
    permissions_requested: [`tool.execute:${capabilityId}`],
    resources: {
      entrypoint,
      manifests: [`${entrypoint}/tool.manifest.json`],
    },
    pricing: { model: "free" },
    categories: ["first-party"],
    tags: ["first-party", capabilityId],
  };
}

export const FIRST_PARTY_PACKAGE_SEEDS: ReadonlyArray<FirstPartyPackageSeed> = [
  {
    package_id: "pkg.adam",
    kind: "agent",
    capability_id: "adam",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: agentManifest(
      "pkg.adam",
      "adam",
      "Adam",
      "First-party orchestrator agent",
      "0.1.0",
      "agents/adam",
      [
        "orchestration.delegate:nova",
        "orchestration.delegate:orion",
        "orchestration.delegate:astra",
        "orchestration.delegate:pixel",
      ],
    ),
  },
  {
    package_id: "pkg.nova",
    kind: "agent",
    capability_id: "nova",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: agentManifest(
      "pkg.nova",
      "nova",
      "Nova",
      "First-party content creation agent",
      "0.1.0",
      "agents/nova",
      ["skill.invoke:writing", "tool.execute:web-search"],
    ),
  },
  {
    package_id: "pkg.orion",
    kind: "agent",
    capability_id: "orion",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: agentManifest(
      "pkg.orion",
      "orion",
      "Orion",
      "First-party analysis agent",
      "0.1.0",
      "agents/orion",
      ["skill.invoke:analysis", "tool.execute:web-search"],
    ),
  },
  {
    package_id: "pkg.astra",
    kind: "agent",
    capability_id: "astra",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: agentManifest(
      "pkg.astra",
      "astra",
      "Astra",
      "First-party SEO agent",
      "0.1.0",
      "agents/astra",
      ["skill.invoke:seo", "tool.execute:seo-audit", "tool.execute:web-search"],
    ),
  },
  {
    package_id: "pkg.pixel",
    kind: "agent",
    capability_id: "pixel",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: agentManifest(
      "pkg.pixel",
      "pixel",
      "Pixel",
      "First-party image / design agent",
      "0.1.0",
      "agents/pixel",
      ["skill.invoke:image-generation", "tool.execute:image-generate"],
    ),
  },
  {
    package_id: "pkg.skill.writing",
    kind: "skill",
    capability_id: "skill.writing",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: skillManifest(
      "pkg.skill.writing",
      "skill.writing",
      "Writing",
      "First-party writing skill",
      "0.1.0",
      "skills/writing",
    ),
  },
  {
    package_id: "pkg.skill.analysis",
    kind: "skill",
    capability_id: "skill.analysis",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: skillManifest(
      "pkg.skill.analysis",
      "skill.analysis",
      "Analysis",
      "First-party analysis skill",
      "0.1.0",
      "skills/analysis",
    ),
  },
  {
    package_id: "pkg.skill.seo",
    kind: "skill",
    capability_id: "skill.seo",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: skillManifest(
      "pkg.skill.seo",
      "skill.seo",
      "SEO",
      "First-party SEO skill",
      "0.1.0",
      "skills/seo",
    ),
  },
  {
    package_id: "pkg.skill.image-generation",
    kind: "skill",
    capability_id: "skill.image-generation",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: skillManifest(
      "pkg.skill.image-generation",
      "skill.image-generation",
      "Image Generation",
      "First-party image brief / generation skill",
      "0.1.0",
      "skills/image-generation",
    ),
  },
  {
    package_id: "pkg.tool.web-search",
    kind: "tool",
    capability_id: "web-search",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: toolManifest(
      "pkg.tool.web-search",
      "web-search",
      "Web Search",
      "First-party web search tool",
      "0.1.0",
      "tools/web-search",
    ),
  },
  {
    package_id: "pkg.tool.file-read-write",
    kind: "tool",
    capability_id: "file-read-write",
    version: "0.1.0",
    default_grant_enabled: false,
    manifest: toolManifest(
      "pkg.tool.file-read-write",
      "file-read-write",
      "File Read/Write",
      "First-party sandboxed file tool",
      "0.1.0",
      "tools/file-read-write",
    ),
  },
  {
    package_id: "pkg.tool.seo-audit",
    kind: "tool",
    capability_id: "seo-audit",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: toolManifest(
      "pkg.tool.seo-audit",
      "seo-audit",
      "SEO Audit",
      "First-party SEO audit stub (no external network)",
      "0.1.0",
      "tools/seo-audit",
    ),
  },
  {
    package_id: "pkg.tool.image-generate",
    kind: "tool",
    capability_id: "image-generate",
    version: "0.1.0",
    default_grant_enabled: false,
    manifest: toolManifest(
      "pkg.tool.image-generate",
      "image-generate",
      "Image Generate",
      "First-party image generation stub (side-effect)",
      "0.1.0",
      "tools/image-generate",
    ),
  },
  {
    package_id: "pkg.workflow.content-campaign",
    kind: "workflow",
    capability_id: "content-campaign",
    version: "0.1.0",
    default_grant_enabled: true,
    manifest: {
      id: "pkg.workflow.content-campaign",
      kind: "workflow",
      version: "0.1.0",
      publisher: "at72",
      display_name: "Content Campaign",
      description: "Declarative campaign: brief → Nova+Astra+Pixel fan-out → checkpoint",
      icons: [],
      contracts: { ...CONTRACTS },
      permissions_requested: [],
      resources: {
        entrypoint: "workflows/content-campaign",
        manifests: ["workflows/content-campaign/workflow.manifest.json"],
      },
      pricing: { model: "free" },
      categories: ["first-party", "workflow"],
      tags: ["first-party", "content-campaign"],
    },
  },
] as const;
